---

sudo: 'required'

language: 'python'
python: '2.7'

env:
  - distro: 'ubuntu1604'
    init: '/lib/systemd/systemd'
  - distro: 'debian8'
    init: '/lib/systemd/systemd'

install:
  - 'pip install ansible==2.1'
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - 'ansible-playbook tests/main.yml -i tests/inventory --syntax-check'
  - 'ansible-playbook tests/main.yml -i tests/inventory --connection=local'
  - >
    ansible-playbook tests/main.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - >
    curl -k -s -o /dev/null -w "%{http_code}" http://localhost:8080
    | grep -q '301'
    && (echo 'HTTPS test: pass' && exit 0)
    || (echo 'HTTPS test: fail' && exit 1)
  - >
    curl -k -s -o /dev/null -w "%{http_code}" https://localhost:8081
    | grep -q '200'
    && (echo 'HTTPS test: pass' && exit 0)
    || (echo 'HTTPS test: fail' && exit 1)
