---
language: "python"
python: "2.7"

env:
  - SITE_AND_INVENTORY="tests/test.yml -i tests/inventory"

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y curl"

install:
  - "pip install ansible==1.6.2"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

before_script:
  - "cd tests && node server &"
  - "sleep 3"
  - "chmod 777 /tmp/testproject.sock"

script:
  - "ansible-playbook $SITE_AND_INVENTORY --syntax-check"
  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvvv"
  - >
    ansible-playbook $SITE_AND_INVENTORY --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - >
    curl -s -o /dev/null -w "%{http_code}" http://localhost:8080
    | grep -q '200'
    && (echo 'Status code test: pass' && exit 0)
    || (echo 'Status code test: fail' && exit 1)